#!/usr/bin/env bash
# Install nginx on my web-01 listening on port 80
# return a page that contains the string Hello World! when querying using curl

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo 'Hello World!' | sudo tee /var/www/html/index.nginx-debian.html
sudo service nginx start
