#!/usr/bin/env bash
# configures a brand new Ubuntu machine to the requirements
# Configure Nginx so that its HTTP response contains a custom header (on web-01 and web-02)
# The name of the custom HTTP header must be X-Served-By
# The value of the custom HTTP header must be the hostname of the server Nginx is running on

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'

echo 'Hello World!' | sudo tee /var/www/html/index.html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/m_404.html > /dev/null

printf %s "server {
        listen 80 default_server;
        listen [::]:80 default_server;
        add_header X-Served-By $HOSTNAME;
        root /var/www/html;

        index index.html index.htm index.nginx-debian.html;

        server_name _;
        error_page 404 /m_404.html;
        location = /m_404.html {
                internal;
                root /var/www/html;
        }

        location = /redirect_me {
                return 301 https://www.youtube.com/;
        }
}" | sudo tee /etc/nginx/sites-available/default > /dev/null

sudo service nginx restart
