#!/usr/bin/env bash
# Install and configure HAproxy on my lb-01 server.
# Configure HAproxy so that it send traffic to web-01 and web-02
# Distribute requests using a roundrobin algorithm
# Make sure that HAproxy can be managed via an init script

sudo apt-get -y update && sudo apt-get -y upgrade

#Add HAProxy Personal Package Archive
sudo apt-get -y install software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.5

sudo apt-get -y update
sudo apt-get -y install haproxy

#configture proxy
sudo cp -a /etc/haproxy/haproxy.cfg{,.orig}

printf %s "frontend haproxy-main
	bind *:80
	mode http
	default_backend nginx_webservers

backend nginx_webservers
	balance roundrobin
	server 218778-web-01	18.215.160.22:80 check
	server 218778-web-02	18.210.14.26:80 check" | sudo tee -a /etc/haproxy/haproxy.cfg

sudo service haproxy restart
