#!/usr/bin/env bash
# reads /etc/passwd file and prints username group id and
#	Home directory path for the user, user id password and shell/command

while IFS=':' read -r name password id group_id info home shell
do
	echo "The user $name is part of the $group_id gang, lives in $home"\
	"and rides $shell. $id's place is protected by the passcode"\
	"$password, more info about the user here: $info"
done < /etc/passwd
