#!/usr/bin/env bash
# Displays 1 to 20:
#	and bad luck from China in iteration 4, bad luck from Japan in iteration 9
#	and bad luck from Italy in iteration 17

n=1
while [ "$n" -le 20 ]
do
	case $n in
		4) echo "$n"; echo "bad luck from China"
			;;
		9) echo "$n"; echo "bad luck from Japan"
			;;
		17) echo "$n"; echo "bad luck from Italy"
			;;
		*) echo "$n"
			;;
	esac
	n="$(( n + 1 ))"
done
