#!/usr/bin/env bash
# Configure ufw so that it blocks all incoming traffic, except the following TCP ports:
# 22 (SSH) 443 (HTTPS SSL) 80 (HTTP)

sudo apt -y update
sudo apt -y install ufw
sudo sed -i 's/IPV6=.*/IPV6=yes' /etc/default/ufw
sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw allow ssh
sudo ufw allow http
sudo ufw allow https
sudo ufw disable
sudo ufw enable
