#!/usr/bin/env bash
# gets Apache to run on the container and to return a page containing Hello
#   Holberton when querying the root of it.

echo "Servername localhost" >> /etc/apache2.conf
service apache2 start
